##############################################
# Deployment groups
- id: primary-standalone-database
  type: group
  role: [primary-standalone-database]
  tasks: [pre_hiera_config, hiera, fuel_pkgs, globals, tools, logging, netconfig,
    hosts, firewall, database-firewall, deploy_start, primary-cluster,
    database-virtual-ip, primary-cluster-haproxy, openstack-haproxy-stats,
    primary-database]
  parameters:
    strategy:
      type: one_by_one

- id: standalone-database
  type: group
  role: [standalone-database]
  tasks: [pre_hiera_config, hiera, fuel_pkgs, globals, tools, logging, netconfig,
    hosts, firewall, database-firewall, deploy_start, cluster,
    database-virtual-ip, cluster-haproxy, openstack-haproxy-stats, database]
  parameters:
    strategy:
      type: parallel

# Deployment tasks
- id: database-hiera-override
  type: puppet
  version: 2.0.0
  role: ['/.*/']
  requires: [pre_hiera_config]
  required_for: [pre_deployment_end]
  parameters:
    puppet_manifest: "database_hiera_override.pp"
    puppet_modules: "/etc/puppet/modules"
    timeout: 120

- id: database-firewall
  type: puppet
  version: 2.0.0
  role: [primary-standalone-database, standalone-database]
  requires: [globals, firewall]
  required_for: [primary-cluster, cluster, primary-database, database]
  parameters:
    puppet_manifest: "database_firewall.pp"
    puppet_modules: "/etc/puppet/modules"
    timeout: 120


- id: database-haproxy
  type: puppet
  version: 2.0.0
  role: [primary-standalone-database, standalone-database]
  required_for: [primary-database, database, deploy_end]
  requires: [deploy_start, database-virtual-ip, primary-cluster-haproxy,
    cluster-haproxy, openstack-haproxy-stats]
  parameters:
    puppet_manifest: "database-haproxy.pp"
    puppet_modules: "/etc/puppet/modules"
    timeout: 3600

- id: database-virtual-ip
  type: puppet
  version: 2.0.0
  role: [primary-standalone-database, standalone-database]
  required_for: [primary-database, database, deploy_end]
  requires: [database-firewall, primary-cluster, cluster]
  parameters:
    puppet_manifest: "/etc/puppet/modules/osnailyfacter/modular/virtual_ips/virtual_ips.pp"
    puppet_modules: "/etc/puppet/modules"
    timeout: 3600

